export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS='REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';

//控制loading
export const PURCAHSE_BURGER_START ='PURCAHSE_BURGER_START';
//成功后重定向到主界面
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

//auth
export const AUTH_STRAT= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
//logout
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//清空order
export const CLEAR_ORDERS = 'CLEAR_ORDERS';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
